import { buildPeriodTable, CHANNELS, compileStream, streamLength } from "../tools/music.mjs";
import { DRUMS, INSTRUMENTS, SONGS, SOUND_EFFECTS } from "./songs.mjs";

const CONSTANT_VOLUME_AND_HALT = 0x30;
const SFX_CHANNEL_INDEX = { pulse2: 1, noise: 3 };

function toConstantName(camelCase) {
  return camelCase.replace(/([a-z])([A-Z])/g, "$1_$2").toUpperCase();
}

function toByteList(bytes) {
  const lines = [];
  for (let index = 0; index < bytes.length; index += 16) {
    lines.push(`  ${bytes.slice(index, index + 16).map((byte) => `0x${byte.toString(16).padStart(2, "0")}`).join(", ")},`);
  }
  return lines.join("\n");
}

function compileSong(name, song) {
  const streams = {};
  for (const channel of CHANNELS) {
    const part = song[channel];
    if (!part) continue;
    streams[channel] = compileStream(part.notes, {
      framesPerSixteenth: song.framesPerSixteenth,
      instrument: part.instrument ? INSTRUMENTS[part.instrument].index : undefined,
      drums: DRUMS,
      loop: song.loop,
    });
  }

  const lengths = Object.entries(streams).map(([channel, bytes]) => [channel, streamLength(bytes)]);
  const [firstChannel, firstLength] = lengths[0];
  for (const [channel, length] of lengths) {
    if (song.loop && length !== firstLength) {
      throw new Error(`Song "${name}": ${channel} lasts ${length} frames but ${firstChannel} lasts ${firstLength}`);
    }
  }
  return streams;
}

export function buildAudioData() {
  const declarations = [];
  const songPointers = [];
  const songNames = Object.keys(SONGS);

  for (const name of songNames) {
    const streams = compileSong(name, SONGS[name]);
    for (const channel of CHANNELS) {
      if (!streams[channel]) {
        songPointers.push("0");
        continue;
      }
      const symbol = `song_${name}_${channel}`;
      declarations.push(`static const unsigned char ${symbol}[] = {\n${toByteList(streams[channel])}\n};`);
      songPointers.push(symbol);
    }
  }

  const effectNames = Object.keys(SOUND_EFFECTS);
  const effectPointers = [];
  const effectChannels = [];
  for (const name of effectNames) {
    const effect = SOUND_EFFECTS[name];
    const symbol = `sfx_${name}`;
    const bytes = compileStream(effect.notes, {
      instrument: effect.instrument ? INSTRUMENTS[effect.instrument].index : undefined,
      drums: DRUMS,
    });
    declarations.push(`static const unsigned char ${symbol}[] = {\n${toByteList(bytes)}\n};`);
    effectPointers.push(symbol);
    effectChannels.push(SFX_CHANNEL_INDEX[effect.channel]);
  }

  const periods = buildPeriodTable();
  const instruments = Object.values(INSTRUMENTS).sort((first, second) => first.index - second.index);

  const header = `// Generated by music/index.mjs - do not edit by hand
#ifndef AUDIO_DATA_H
#define AUDIO_DATA_H

${songNames.map((name, index) => `#define SONG_${toConstantName(name)} ${index}`).join("\n")}
#define SONG_COUNT ${songNames.length}

${effectNames.map((name, index) => `#define SFX_${toConstantName(name)} ${index}`).join("\n")}

extern const unsigned char period_low[${periods.length}];
extern const unsigned char period_high[${periods.length}];
extern const unsigned char instrument_control[${instruments.length}];
extern const unsigned char instrument_decay[${instruments.length}];
extern const unsigned char instrument_sustain[${instruments.length}];
extern const unsigned char song_loops[${songNames.length}];
extern const unsigned char * const song_streams[${songPointers.length}];
extern const unsigned char * const sfx_streams[${effectNames.length}];
extern const unsigned char sfx_channels[${effectNames.length}];

#endif
`;

  const source = `// Generated by music/index.mjs - do not edit by hand
#include "audio_data.h"

const unsigned char period_low[${periods.length}] = {
${toByteList(periods.map((period) => period & 0xff))}
};

const unsigned char period_high[${periods.length}] = {
${toByteList(periods.map((period) => period >> 8))}
};

const unsigned char instrument_control[${instruments.length}] = {
${toByteList(instruments.map(({ duty, volume }) => (duty << 6) | CONSTANT_VOLUME_AND_HALT | volume))}
};

const unsigned char instrument_decay[${instruments.length}] = {
${toByteList(instruments.map(({ decayFrames }) => decayFrames))}
};

const unsigned char instrument_sustain[${instruments.length}] = {
${toByteList(instruments.map(({ sustain }) => sustain))}
};

const unsigned char song_loops[${songNames.length}] = {
${toByteList(songNames.map((name) => (SONGS[name].loop ? 1 : 0)))}
};

${declarations.join("\n\n")}

const unsigned char * const song_streams[${songPointers.length}] = {
  ${songPointers.join(",\n  ")},
};

const unsigned char * const sfx_streams[${effectNames.length}] = {
  ${effectPointers.join(",\n  ")},
};

const unsigned char sfx_channels[${effectNames.length}] = {
${toByteList(effectChannels)}
};
`;

  return { header, source };
}
