// Sound driver: four music channels (pulse 1, pulse 2, triangle, noise) plus two
// sound effect channels that temporarily take over pulse 2 and noise. Streams are
// generated by music/index.mjs; see tools/music.mjs for the byte format.
#include "audio.h"
#include "nes.h"

#define APU_REG(offset) (*(volatile u8 *)(0x4000 + (offset)))
#define APU_STATUS (*(volatile u8 *)0x4015)

#define CHANNEL_PULSE_1 0
#define CHANNEL_PULSE_2 1
#define CHANNEL_TRIANGLE 2
#define CHANNEL_NOISE 3
#define CHANNEL_SFX_PULSE 4
#define CHANNEL_SFX_NOISE 5
#define CHANNEL_COUNT 6
#define MUSIC_CHANNEL_COUNT 4

#define OP_REST 0x6C
#define OP_INSTRUMENT 0x70
#define OP_DURATION 0x80
#define OP_LOOP 0xFE
#define OP_END 0xFF

#define TRIANGLE_OCTAVE_SHIFT 12
#define TRIANGLE_ON 0xFF
#define TRIANGLE_OFF 0x80
#define SWEEP_DISABLED 0x08
#define NO_PERIOD_HIGH 0xFF

static const u8 *stream_start[CHANNEL_COUNT];
static const u8 *stream_position[CHANNEL_COUNT];
static u8 active[CHANNEL_COUNT];
static u8 timer[CHANNEL_COUNT];
static u8 duration[CHANNEL_COUNT];
static u8 instrument[CHANNEL_COUNT];
static u8 volume[CHANNEL_COUNT];
static u8 decay_timer[CHANNEL_COUNT];
static u8 note[CHANNEL_COUNT];
static u8 sounding[CHANNEL_COUNT];
static u8 last_period_high[2];
static u8 music_playing;
static u8 paused;

static u8 channel;
static u8 command;

static void silence_hardware(void) {
  APU_REG(0x00) = 0x30;
  APU_REG(0x04) = 0x30;
  APU_REG(0x08) = TRIANGLE_OFF;
  APU_REG(0x0C) = 0x30;
  last_period_high[0] = NO_PERIOD_HIGH;
  last_period_high[1] = NO_PERIOD_HIGH;
}

void audio_init(void) {
  APU_STATUS = 0x0F;
  APU_REG(0x01) = SWEEP_DISABLED;
  APU_REG(0x05) = SWEEP_DISABLED;
  for (channel = 0; channel < CHANNEL_COUNT; ++channel) active[channel] = 0;
  music_playing = 0;
  silence_hardware();
}

static void start_stream(u8 target, const u8 *stream) {
  stream_start[target] = stream;
  stream_position[target] = stream;
  active[target] = stream != 0;
  timer[target] = 0;
  duration[target] = 1;
  instrument[target] = 0;
  volume[target] = 0;
  sounding[target] = 0;
}

void music_play(u8 song) {
  const u8 *const *streams = &song_streams[song * MUSIC_CHANNEL_COUNT];
  for (channel = 0; channel < MUSIC_CHANNEL_COUNT; ++channel) start_stream(channel, streams[channel]);
  music_playing = 1;
  silence_hardware();
}

void music_stop(void) {
  for (channel = 0; channel < MUSIC_CHANNEL_COUNT; ++channel) active[channel] = 0;
  music_playing = 0;
  silence_hardware();
}

u8 music_is_playing(void) {
  return music_playing;
}

void sfx_play(u8 effect) {
  start_stream(sfx_channels[effect] == CHANNEL_PULSE_2 ? CHANNEL_SFX_PULSE : CHANNEL_SFX_NOISE, sfx_streams[effect]);
}

// Reads commands until the next note or rest, then starts it
static void advance_stream(void) {
  const u8 *position = stream_position[channel];

  for (;;) {
    command = *position++;
    if (command == OP_END) {
      active[channel] = 0;
      sounding[channel] = 0;
      volume[channel] = 0;
      stream_position[channel] = position;
      return;
    }
    if (command == OP_LOOP) {
      position = stream_start[channel];
      continue;
    }
    if (command >= OP_DURATION) {
      duration[channel] = command & 0x7F;
      continue;
    }
    if (command >= OP_INSTRUMENT) {
      instrument[channel] = command & 0x0F;
      continue;
    }
    break;
  }

  stream_position[channel] = position;
  timer[channel] = duration[channel];

  if (command == OP_REST) {
    sounding[channel] = 0;
    volume[channel] = 0;
    return;
  }

  note[channel] = command;
  sounding[channel] = 1;
  volume[channel] = instrument_control[instrument[channel]] & 0x0F;
  decay_timer[channel] = instrument_decay[instrument[channel]];
}

static void apply_decay(void) {
  u8 decay = instrument_decay[instrument[channel]];
  if (!sounding[channel] || decay == 0) return;
  if (--decay_timer[channel]) return;

  decay_timer[channel] = decay;
  if (volume[channel] > instrument_sustain[instrument[channel]]) --volume[channel];
}

static void write_pulse(u8 hardware, u8 source) {
  u8 base = hardware << 2;
  u8 control = instrument_control[instrument[source]] & 0xF0;
  u8 high;

  if (!active[source] || !sounding[source]) {
    APU_REG(base) = 0x30;
    return;
  }

  APU_REG(base) = control | volume[source];
  APU_REG(base + 2) = period_low[note[source]];
  high = period_high[note[source]];
  // Rewriting the high byte restarts the waveform and clicks, so only do it on change
  if (high != last_period_high[hardware]) {
    APU_REG(base + 3) = high;
    last_period_high[hardware] = high;
  }
}

static void write_triangle(void) {
  u8 pitch;
  // Cutting the last frame of each note keeps repeated bass notes articulated
  if (!active[CHANNEL_TRIANGLE] || !sounding[CHANNEL_TRIANGLE] || timer[CHANNEL_TRIANGLE] == 0) {
    APU_REG(0x08) = TRIANGLE_OFF;
    return;
  }
  pitch = note[CHANNEL_TRIANGLE] + TRIANGLE_OCTAVE_SHIFT;
  APU_REG(0x08) = TRIANGLE_ON;
  APU_REG(0x0A) = period_low[pitch];
  APU_REG(0x0B) = period_high[pitch];
}

static void write_noise(u8 source) {
  if (!active[source] || !sounding[source]) {
    APU_REG(0x0C) = 0x30;
    return;
  }
  APU_REG(0x0C) = 0x30 | volume[source];
  APU_REG(0x0E) = note[source] & 0x0F;
  APU_REG(0x0F) = 0x08;
}

void audio_set_paused(u8 is_paused) {
  paused = is_paused;
  silence_hardware();
}

void audio_update(void) {
  if (paused) return;

  for (channel = 0; channel < CHANNEL_COUNT; ++channel) {
    if (!active[channel]) continue;
    if (timer[channel] == 0) advance_stream();
    if (!active[channel]) continue;
    apply_decay();
    --timer[channel];
  }

  if (music_playing && !active[CHANNEL_PULSE_1] && !active[CHANNEL_PULSE_2] && !active[CHANNEL_TRIANGLE] &&
      !active[CHANNEL_NOISE]) {
    music_playing = 0;
  }

  write_pulse(0, CHANNEL_PULSE_1);

  if (active[CHANNEL_SFX_PULSE]) {
    write_pulse(1, CHANNEL_SFX_PULSE);
  } else {
    write_pulse(1, CHANNEL_PULSE_2);
  }

  write_triangle();
  write_noise(active[CHANNEL_SFX_NOISE] ? CHANNEL_SFX_NOISE : CHANNEL_NOISE);
}
